services:
  mongo:
    image: mongo:latest
    container_name: ${MONGO_CONTAINER_NAME}
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
      - ./${MONGO_DATA_DIR}:/${MONGO_DATA_DOCKER_DIR}

volumes:
  mongo_data:
    driver: local
