services:
  mongo:
    image: mongo:latest
#    container_name: ${MONGO_CONTAINER_NAME}
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    ports:
      - "${MONGO_PORT_HOST}:${MONGO_PORT}"
    volumes:
      - mongo_data:/data/db
      - ./${MONGO_DATA_DIR}:/${MONGO_DATA_DOCKER_DIR}
    networks:
      - backend

  postgres:
    image: postgres:latest
#    container_name: ${POSTGRES_CONTAINER_NAME}
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    ports:
      - "${POSTGRES_PORT_HOST}:${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./${POSTGRES_DATA_DIR}:/${POSTGRES_DATA_DOCKER_DIR}
    networks:
      - backend

  fastapi:
    build:
      context: ./server
      dockerfile: Dockerfile
#    container_name: fastapi
    restart: always
    ports:
      - "${FASTAPI_PORT_HOST}:${FASTAPI_PORT_CONTAINER}"
    volumes:
      - ./${MONGO_DATA_DIR}:/${MONGO_DATA_DIR}
      - ./${POSTGRES_DATA_DIR}:/${POSTGRES_DATA_DIR}
    environment:
      - MONGO_URI=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo:${MONGO_PORT}/${MONGO_DB_NAME}?authSource=admin
      - POSTGRES_URI=postgresql+asyncpg://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB_NAME}
    command: ["python", "main.py"]
    depends_on:
      - mongo
      - postgres
    networks:
      - backend

  fastapi_dev:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
#    container_name: fastapi_dev
    restart: always
    ports:
      - "${FASTAPI_DEV_PORT_HOST}:${FASTAPI_PORT_CONTAINER}"
      - "5678:5678"  # port debugowania
    volumes:
      - ./server:/app
      - ./${MONGO_DATA_DIR}:/${MONGO_DATA_DIR}
      - ./${POSTGRES_DATA_DIR}:/${POSTGRES_DATA_DIR}
    environment:
      - MONGO_URI=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo:${MONGO_PORT}/${MONGO_DB_NAME}?authSource=admin
      - POSTGRES_URI=postgresql+asyncpg://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB_NAME}
    command: ["python", "main.py"]
    depends_on:
      - mongo
      - postgres
    networks:
      - backend

volumes:
  mongo_data:
    driver: local
  postgres_data:
    driver: local

networks:
  backend:
    driver: bridge