services:
  mongo:
    image: mongo:latest
    container_name: mongo_gesture_devices
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
      - ./server/data/json:/json

volumes:
  mongo_data:
    driver: local
